export const types = {
    ADD_TO_CART : "[CAR] ADD_TO_CART",
    REMOVE_ONE_FROM_CART: "[CAR] REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART: "[CAR] REMOVE_ALL_FROM_CART",
    CLEAR_CART: "[CAR] CLEAR_CART",
    
    ADD_PRODUCT: "[PRODUCT] ADD_PRODUCT",
    EDIT_PRODUCT: "[PRODUCT] EDIT PRODUCT",
    REMOVE_ONE_PRODUCT: "[PRODUCT] REMOVE_ONE_PRODUCT",

    OPEN_MODAL: "[UI] OPEN_MODAL",
    CLOSE_MODAL: "[UI CLOSE_MODAL]"
}
